# Ora-Ora-Ora configuration example
#
# Copy or rename this file to `config.yaml` to activate.
# Fields not set will fall back to built-in defaults.

# Ollama server host (protocol + host:port)
ollamaHost: http://localhost:11434

# Default model name used by the agent
model: llama3

# Data locations for notes and search index
data:
  # Directory to store JSONL notes (e.g., data/notes/YYYY-MM-DD.jsonl)
  notesDir: data/notes
  # Directory to store Bleve index files
  indexDir: data/index

# TUI options
tui:
  # Default width hint for rendering
  width: 80

