name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
      - name: Go cache
        uses: actions/cache@v4
        with:
          path: .gocache
          key: ${{ runner.os }}-gocache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gocache-
      - name: Run tests
        run: make -C dev test

